### ISSUE TITLE
Doesn't return the same number of results as Zillow website

### ISSUE THREAD

**Issue by bran22** [cermak-petr/actor-zillow-api-scraper#1]
Hi!  Thanks very much for making and publishing this actor!  I gave it spin today, and it seems extremely useful!

I have a question about something I noticed today while running it.  I tried running the actor using the query term "atlanta, ga" and the type "for sale" while also running the same query directly on the Zillow website, and I got a pretty large difference in the number of results (~3200 vs ~4400 respectively, so a lot fewer results from the actor).  I noticed that the `queryRegionHomes` method has some built-in filter states for the search types "for rent" and "for sale by owner", but there's no case condition for just the ordinary "for sale".  **I'm wondering if there are any "default" filters that are being used to restrict the search results?**

I seem to be able to get a similar _quantity_ of results on the Zillow website by unchecking all the search filter boxes under "For Sale" except for "By Agent" and "By Owner", but I can't verify whether that is the true cause of the scrape result discrepancy.

**Comment by omardoma** [comment]
Facing the same issue here, there is a discrepancy from the count I see on Zillow. Also, if I define the type as `Sold` I still get `For Sale` properties in the results.

**Comment by pocesar** [comment]
this should be fixed in `latest`
