### ISSUE TITLE
Can't scrape a list of ZPIDs. 

### ISSUE THREAD

**Issue by fmarcanob** [cermak-petr/actor-zillow-api-scraper#14]
Hi there! After a couple hundred extractions, the log starts saying "Data extraction failed - zpid: xxxxxxx" a lot, until it finished all the list. Anything that can be done? Thank you very much.

I have attached log file and screenshot.

[r7Y43IxfnODwpu9q5.log](https://github.com/cermak-petr/actor-zillow-api-scraper/files/5954213/r7Y43IxfnODwpu9q5.log)
![Screenshot 2021-02-09 at 16 57 13](https://user-images.githubusercontent.com/78824219/107427546-e8cac000-6af7-11eb-99af-5626204ee91d.png)

**Comment by pocesar** [comment]
@fmarcanob you can set your version to `beta` on the platform, it's ongoing changes. it should work better

**Comment by fmarcanob** [comment]
> @fmarcanob you can set your version to `beta` on the platform, it's ongoing changes. it should work better

Thank you for your answer. I wasn't capable of doing much with beta, because it doesn't allow to use custom proxies. Is it possible to change this? With the stable version, I was able to extract amounts between 250-800 for each run, instead of the 8k (using 250 USA proxies). In the end, it always goes to that data extraction failed error and I have to stop and start running again minus the IDs that were processed with success.

**Comment by pocesar** [comment]
your proxies are wrong, you have a lot of tabs after the urls. I couldn't find any run using `beta`. the task is also configured to max 200 items
![image](https://user-images.githubusercontent.com/461084/107471835-8ea81a00-6b4c-11eb-935c-a3e88d813acc.png)

I've added a new task (called beta-zillow, check the tasks section) for you with changes to the input
