### ISSUE TITLE
Listed By property owner field

### ISSUE THREAD

**Issue by deepaksapkale** [cermak-petr/actor-zillow-api-scraper#15]
This scrapper doesn't show if property is listed by owner or not.

**Comment by ekorkuch** [comment]
it does show if listed by owner in the "full" results (uncheck "Simple Results") - the attribute is: "isListedByOwner":true and is column AB in the CSV export.  However, the contact info for "isListedByOwner" where TRUE is not provided - listingProvider/agentName and /phoneNumber are blank.  I'm not sure if this is a privacy protection policy of Zillow's API or a bug that can be fixed.

**Comment by deepaksapkale** [comment]
Thanks for response, I highly appreciate it. I was able to fetch data with "isListedByOwner" flag. However, when we open link, website says the "Listed by management company". Usually when a data is flagged as "isListedbyOwner", website shows "Listed by property owner". However website shows that it is listed by management company, even when in fetched data, it is marked as true for "isListedByOwner" Look at this example, 
https://www.zillow.com/homedetails/7403-Vanalden-Ave-Reseda-CA-91335/19905362_zpid/
--

**Comment by pocesar** [comment]
you can use the `contactFormRenderData` and search for the hidden data there. have the agents and lender information, sometimes the owner information as well
