### ISSUE TITLE
Zestimate

### ISSUE THREAD

**Issue by Hprg** [cermak-petr/actor-zillow-api-scraper#16]
How do we get the output of Zestimate?

**Comment by zpelechova** [comment]
Hi, just add:
```js
async ({ item, data }) => {
  item.zestimate = data.zestimate; // add new array data
  return item; // need to return the item here, otherwise your dataset will be empty
}
```
to Extend output function.

**Comment by Hprg** [comment]
I have added them to the extended output but returning error. 

(data) => {
    return {};
}async ({ item, data }) => { item.zestimate = data.zestimate; // add new array data return item; // need to return the item here, otherwise your dataset will be empty }

**Comment by Hprg** [comment]
I just need to extract the zesitmate and Parcel number.  Thank you

**Comment by zpelechova** [comment]
I have it like this and it works...
It should be similar with the parcel number

![image](https://user-images.githubusercontent.com/39551460/108493430-98e1bb00-72a6-11eb-9c05-f5cda1bd37e7.png)

**Comment by pocesar** [comment]
note that this new format requires `beta` version

**Comment by Hprg** [comment]
Thank you for your help I have put the estimate in and its working but when I do the parcel number nothing comes up.  This is what I am entering

async ({ item, data }) => { 
    item.zestimate = data.zestimate; // add new array data 
    return item; // need to return the item here, otherwise your dataset will be empty 
    };
    async ({ item, data }) => { 
    item.parcelnumber = data.parcelnumber; // add new array data 
    return item; // need to return the item here, otherwise your dataset will be empty 
    }

**Comment by pocesar** [comment]
@Hprg that's not valid code, you need to use:

```js
async ({ item, data }) => {
  item.zestimate = data.zestimate; // add new array data
  item.parcelnumber = data.parcelNumber;

  return item; // need to return the item here, otherwise your dataset will be empty
}
```
