### ISSUE TITLE
When input several urls and max input, only get results from the first url

### ISSUE THREAD

**Issue by zpelechova** [cermak-petr/actor-zillow-api-scraper#18]
https://my.apify.com/view/runs/lX1bSgwggwgRRQbJI

**Comment by pocesar** [comment]
yeah, this is the intended behavior. since searches can have a theoretical infinite amount of items and details urls are 1:1, if you place it before, it will be extracted first, then the search one

**Comment by zpelechova** [comment]
Would it be cool to get eg 10 results for each and not the whole? It is like that in some other actors... E.g. Gmaps.
