### ISSUE TITLE
Dates Extracted as 10 digit number with zeros at the end

### ISSUE THREAD

**Issue by amandaliddle** [cermak-petr/actor-zillow-api-scraper#22]
The last date sold variable extracts as a string of 10 digits and I don't know how to convert it to an actual date

**Comment by pocesar** [comment]
it's a unix timestamp in milliseconds, you can use this as `new Date(timestamphere).toISOString()` or if you're using other languages, like PHP that consider timestamps to be in seconds, you just divide by 1000
