### ISSUE TITLE
fetch MLS ID in output dataset see screenshot attached for reference 

### ISSUE THREAD

**Issue by Erinapify** [cermak-petr/actor-zillow-api-scraper#26]
![mlsid](https://user-images.githubusercontent.com/81418188/112623027-1e1f3900-8e2c-11eb-8783-505cefc827a9.jpg)

**Comment by pocesar** [comment]
it's in the `data.mlsid` inside extend output function, you can add it as:

```js
async ({ item, data }) => {
   item.mlsid = data.mlsid;
   return item;
}
```
