### ISSUE TITLE
Input field Type is not working

### ISSUE THREAD

**Issue by Mr-Royce** [cermak-petr/actor-zillow-api-scraper#27]
Ever since some breaking changes were made about a month or so ago, the Type section does not work. Regardless of selection only For sale properties are always returned. I have tested this extensively on a new actor task to ensure it wasn't any changes I made, but I never get any results besides for sale.

**Comment by omardoma** [comment]
I am facing the same issue. Searching for `Sold` properties returns `For Sale` ones in the results. @cermak-petr @pocesar any pointers on what can be modified in the code to fix that?

**Comment by franhodg** [comment]
Same issue here. I have been able to work around by filtering the results, but it does mean that I have to scrape more listings just to reach the Sold properties, which I am looking for.

**Comment by pocesar** [comment]
there's a hotfix on the way, but don't fix the actual issue yet. the actual update will come later this week

**Comment by pocesar** [comment]
the scraper is much more precise and shouldn't give you unexpected results output from the input filter. even better if you use an url having a `searchQueryState`
