### ISSUE TITLE
Support dynamic minimum date

### ISSUE THREAD

**Issue by neirbonhoj** [cermak-petr/actor-zillow-api-scraper#29]
Would you mind supporting a function or date range for the minimum date field? I.e. properties posted today, past 3 days, past 7 days, or a range.

**Comment by pocesar** [comment]
@neirbonhoj that's actually possible, we have a standardized function that we implement for all scrapers. should be done soon

**Comment by pocesar** [comment]
this works now, you can use `today`, `yesterday`, `1 month`, `3 years`, etc
