### ISSUE TITLE
Enable custom polygons in input

### ISSUE THREAD

**Issue by metalwarrior665** [cermak-petr/actor-zillow-api-scraper#30]
Request from a user
```
how can I use your zillow scraper to pass custom polygons (i have list of coordinates)? i do not see this described in your zillow api scraper.
```

Perhaps it can be done easily via Start URLs?

**Comment by pocesar** [comment]
yeah, you already can provide the url containing searchQueryState, usually have the map bounds

**Comment by pocesar** [comment]
works with searchQueryState urls
