### ISSUE TITLE
HOA fee is not collected

### ISSUE THREAD

**Issue by spalfy** [cermak-petr/actor-zillow-api-scraper#35]
Based on the code you try to collect the "HOA fee" info when not in simple mode, but it is not in the results. See attached result set as an example.

[Weymouth dataset_my-task_2021-05-24_05-58-19-788.zip](https://github.com/cermak-petr/actor-zillow-api-scraper/files/6530185/Weymouth.dataset_my-task_2021-05-24_05-58-19-788.zip)

**Comment by pocesar** [comment]
everything can be added to the output using the Extend output function, like `item.HOA = data.monthlyHoaFee`

**Comment by spalfy** [comment]
It works now. Thank you!
You may want to consider adding this to the extended result set by default, as the HOA fee is an important factor when you calculate the price / (rent-costs) ratio. Figuring out the identifiers to use might not be trivial to nontechnical users.
