### ISSUE TITLE
HOA fee is not collected when it appears only in the "Facts and Features" table

### ISSUE THREAD

**Issue by spalfy** [cermak-petr/actor-zillow-api-scraper#36]
In some Zillow listings, the HOA fee has a value under "Facts and Features" but is "N/A" in the "Monthly costs" table (see screenshots). In these cases, the actor does not collect the HOA fee in data.monthlyHoaFee. 

For example: https://www.zillow.com/homedetails/152-E-Bacon-St-APT-C2-Plainville-MA-02762/57493749_zpid/

![missing_HOA2](https://user-images.githubusercontent.com/54693554/121475279-7db9c900-c9c5-11eb-9a4a-14a5562c1998.PNG)
![missing_HOA1](https://user-images.githubusercontent.com/54693554/121475281-7e525f80-c9c5-11eb-9f09-36a7172ba3a3.PNG)

**Comment by roeiburstein** [comment]
I'd like this feature as well. HOA is missing and should be retrievable. Thank you!

**Comment by pocesar** [comment]
this information is available inside `resoFacts` property on the `data` variable. you can add it to the output. when hoaFee is available at top level, it will be available on the output as well
