### ISSUE TITLE
For sale by owner's number

### ISSUE THREAD

**Issue by badbit0** [cermak-petr/actor-zillow-api-scraper#40]
How can we get the owner's phone number in the output?

![2YMSud5vwv](https://user-images.githubusercontent.com/88742053/130518996-5b56b714-9a01-4a51-acd0-a06f49e5ffcd.png)

**Comment by badbit0** [comment]
I tried the following
item.phone = data.phone;
item.Phone = data.Phone;
item.number = data.number;
item.phonenumber = data.phonenumber;
item.phoneNumber = data.phoneNumber;
item.region_phone_number = data.region_phone_number;
item.areacode = data.areacode;
item.areaCode = data.areaCode;
item.prefix = data.prefix;
item.associationPhone = data.associationPhone;

**Comment by jkessous** [comment]
did anyone manage to set this up?
thanks

**Comment by pocesar** [comment]
you can try to see if this data is available using `"rawOutput": true` to the options. personal information is not added to the output by default
