### ISSUE TITLE
It did not retrieved photos in the simple json modality

### ISSUE THREAD

**Issue by naticio** [cermak-petr/actor-zillow-api-scraper#47]
It did not retrieved photos in the simple json, should I call complex instead?

![image](https://user-images.githubusercontent.com/34293050/152559155-6571a8ba-b706-4805-aa6a-a3b4847dbc4c.png)

[{
  "address": {
    "streetAddress": "334 E 78th St APT 17",
    "city": "New York",
    "state": "NY",
    "zipcode": "10075",
    "neighborhood": null,
    "community": null,
    "subdivision": null
  },
  "bedrooms": 1,
  "bathrooms": 1,
  "price": 2600,
  "yearBuilt": null,
  "longitude": -73.954315,
  "homeStatus": "FOR_RENT",
  "latitude": 40.77203,
  "description": "**SELF-SHOWING NOW AVAILABLE WITH THE KNOCK APP\n\n**SEND AN INQUIRY TODAY AND TOUR IN PERSON, CONTACT FREE WITHIN MINUTES.**\n\n**NO FEE**\n\n200 CASH for Immediate Lease Start Dates**\nPhotos of similar unit \n\nSpacious 1 Bedroom Apartment on the Upper East Side/Yorkville!\n\n**Apartment Features\n\n-Dishwasher\n-Heat and water included\n-Large closets \n-Natural light throughout \n-3rd floor \n\n**Building Features\n\n-Live in super\n-Pets Allowed \n (Cats Only)\n-Guarantors accepted \n\nMove in Cost: \nApplication fee $20\nSecurity Deposit \nFirst Month's Rent \n\nSubways: Q, 4, 5, 6\n\nThe neighborhood is full of restaurants, bars, Whole Foods, Equinox, shopping, museums, comedy clubs and more!",
  "livingArea": null,
  "currency": "USD",
  "url": "https://www.zillow.com/homedetails/334-E-78th-St-APT-17-New-York-NY-10075/2120690271_zpid/"
}

**Comment by pocesar** [comment]
the simple JSON is meant for being CSV friendly, and arrays aren't. if you need to add anything even to the simple output, you can use the `Extend output function` and appending the data from the `data` variable
