### ISSUE TITLE
Include Date and Days on Zillow as Custom Field

### ISSUE THREAD

**Issue by anaagladze** [cermak-petr/actor-zillow-api-scraper#48]
Hi, I'm unable to expand the Zillow Scraper to include the date listing was posted and how many days it is on Zillow.

I tried using this: 

async ({ item, data }) => {

  item.dataUpdated = data.date; // add new array data

  return item; // need to return the item here, otherwise your dataset will be empty
}

Can you please help to understand what I'm doing wrong?

**Comment by pocesar** [comment]
`daysOnZillow` is now available by default in simple and full outputs
