### ISSUE TITLE
Redundant 'OR'

### ISSUE THREAD

**Issue by vladyslav-n** [cermak-petr/actor-zillow-api-scraper#54]
https://github.com/cermak-petr/actor-zillow-api-scraper/blob/fc46b9e8253e2da7865f7ba9a02f7c43b9cfc283/src/page-handler.js#L199

It seems to me that in `zpid || zpidUrl` expression `|| zpidUrl` part is redundant as this code is inside `if (zpid) {}` block.

**Comment by pocesar** [comment]
done
