### ISSUE TITLE
FSBO Listing Type doesn't return phone numbers

### ISSUE THREAD

**Issue by labventures** [cermak-petr/actor-zillow-api-scraper#6]
listingProvider/phoneNumber column seems to be empty when trying to scrape FSBO listing types.

The expected result should be the phone number of the Property Owner (see attached screenshot)

![image](https://user-images.githubusercontent.com/73177913/96591471-491dc380-12b5-11eb-8840-12111d609862.png)

**Comment by pocesar** [comment]
it's under `listingProvider.phoneNumber`
